### ISSUE TITLE
template tag in IE seems to skip $parent scope

### ISSUE THREAD

**Issue by hobbit125** [aurelia/html-template-element#2] opened 2015-06-01 13:25 UTC
This code:

``` markup
<div repeat.for = "child of children">
   <template repeat.for="grandchild of child.children">
     ${$parent.$parent.topLevelVariable}
   </template>
</div>
```

Works fine in chrome ($parent.$parent gets you out of the two nested repeats and back up to the top context)

In IE, however, it does not work unless you simply do $parent once 

It would seem that the template polyfill does not to properly establish a context or doesn't nest context appropriately...

**Comment by hobbit125** [comment] 2015-06-01 13:42
More specific example:

```
<table>
<tbody>
  <tr repeat.for="row of reportData">
     <td>${row.id}</td>
      <template repeat.for="child or row.children">
        <td innerHTML.bind="$parent.$parent.formatResult(child)"></td>
      </template>
  </tr>
</tbody>
</table>
```

**Comment by EisenbergEffect** [comment] 2015-06-01 22:57
Can this be reproduced in IE without using a table? Or does this bug only happen when there's a table present with a template element inside it?

**Comment by hobbit125** [comment] 2015-06-02 00:41
After much experimenting, I think this is just a "don't use template tags anywhere inside of table tag structure" thing.  (If you want your app to work in IE.). Its a limitation, but maybe one you can ship with.  I thinly it's just going to prevent any situation where you have a hierarchy of data being rendered in a table (e.g with parent rows and child rows beneath them.) 

Seems you can use template inside td or th, just not in tr or tbody or thead.

**Comment by EisenbergEffect** [comment] 2015-06-02 01:10
Ok, so this and the other issue are basically the same. Can I as one more favor? Could you catalog in this issue the specific markup which does and does not work with tables in IE just to make sure we are clear? With that, we may be able to come up with a workaround.

**Comment by hobbit125** [comment] 2015-06-02 04:29
Yeah will do tomorrow.

**Comment by EisenbergEffect** [comment] 2015-07-22 01:28
I'm going to close this issue since we have this tracked elsewhere.

**Closed as completed by EisenbergEffect** 2015-07-22 01:28 UTC
Labels: bug
